project:
  type: website
  output-dir: docs

website:
  title: "EDA Simplifier"
  navbar:
    left:
      - text: "Reference"
        href: reference/index.html
      - text: "Code of Conduct"
        href: CODE_OF_CONDUCT.html
      - text: "Contributing"
        href: CONTRIBUTING.html
      - text: "Development"
        href: DEVELOPMENT.html
      - text: "Change log"
        href: CHANGELOG.html
     
format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: eda_simplifier
  dir: reference
  sections:
    - title: EDA Tools Simplified
      desc: Functions to help you quickly and easily get high-level EDA visuals 
      contents:
        - simplify.dataset_overview
        - simplify.numeric
        - simplify.categorical_plot
        - simplify.all_distributions
        - simplify._ambiguous_columns_split
        
