name: eda_simplifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pandas>=2.0
  - altair>=5.0
  - numpy>=2.4
  - pytest>=9.0
  - hatch>=1.16
  - pre-commit>=4.3
  - pytest-cov>=7.0
  - pytest-randomly>=4.0
  - pytest-xdist>=3.8
  - ruff>=0.14
  - black>=26.1

  # Pip-only packages
  - pip>=24.0
  - pip:
      - quartodoc>=0.11
      - pytest-raises>=0.11
