#https://github.com/ilyamusabirov/524-actionsdemo/blob/main/.github/workflows/03b-quartodoc-publish.yml
#stuff
name: Render Docs

on:
  #pull_request:
  push:
    branches:
      - main    
  workflow_dispatch:

jobs:
  render-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -e ".[docs]"
          #pip install quartodoc

      # - name: Install hatch
      #   run: |
      #       python -m pip install --upgrade pip
      #       python -m pip install hatch

      # - name: Build documentation using Hatch
      #   run: |
      #       hatch run docs:build

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build quartodoc
        run: |
          quartodoc build --verbose

      - name: Render Quarto site
        run: |
          quarto render

      - name: Publish to gh-pages branch
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
